-- WE GIVE HealthChecksAppUser ROLES IN ORDER TO MAKE DATABASE CRUD OPERATIONS 
-- NEEDED BY ASPNETCORE.HEALTHCHEKCS.UI.SQLSERVER.STORAGE UI STORAGE PROVIDER

ALTER ROLE db_ddladmin ADD MEMBER HealthChecksAppUser
ALTER ROLE db_datareader ADD MEMBER HealthChecksAppUser
ALTER ROLE db_datawriter ADD MEMBER HealthChecksAppUser